from __future__ import annotations

import argparse
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

EXPORT_TARGETS = {"agents", "claude", "cursor", "aider", "copilot"}
EXPORT_BEGIN = "<!-- AI_RAIL_EXPORT_BEGIN -->"
EXPORT_END = "<!-- AI_RAIL_EXPORT_END -->"


@dataclass
class BrainContext:
    active_issue_summary: Callable[[], dict[str, Any]]
    brain_dir: Callable[[], Path]
    cfg: Callable[[], dict[str, Any]]
    changed_files: Callable[[], list[str]]
    checks_path: Callable[[], Path]
    checks_result: Callable[[], str]
    configured_repository: Callable[[dict[str, Any]], str]
    copy_to_clipboard: Callable[[str], bool]
    current_branch: Callable[[], str]
    handoff_state_path: Callable[[str], Path]
    next_backup_path: Callable[[Path], Path]
    rail_dir: Callable[[], Path]
    recent_history_lines: Callable[[int], list[str]]
    git_status_porcelain: Callable[[], str]
    review_path: Callable[[], Path]
    root: Callable[[], Path]
    safe_read_text: Callable[..., str]
    print_text: Callable[[str], None]
    utc_now: Callable[[], str]
    version: str


def next_safe_action(checks: str, has_active: bool, files: list[str]) -> str:
    if not has_active:
        return "Start the next task with `rail next`."
    if files and checks != "passed":
        return "Run `rail verify` before shipping."
    if files and checks == "passed":
        return "Ask an AI reviewer to inspect the handoff/review, then run `rail ship \"type(scope): message\"` when approved."
    return "Continue the active task or run `rail verify` if implementation is complete."


def render_project_brain(ctx: BrainContext, max_history: int = 5) -> dict[str, str]:
    config = ctx.cfg()
    active_issue = ctx.active_issue_summary()
    checks = ctx.checks_result()
    status = ctx.git_status_porcelain()
    files = ctx.changed_files()

    project_name = config.get("project_name") or ctx.root().name
    repository = ctx.configured_repository(config)
    check_commands = config.get("checks") or []

    project = f"""# Project

- Name: {project_name}
- Repository: {repository}
- Root: {ctx.root()}
- AI Rail version: {ctx.version}

## Purpose

This repo uses AI Rail as a local-first project brain and workflow rail for AI-assisted development.

## Configured checks
{chr(10).join(f"- `{cmd}`" for cmd in check_commands) if check_commands else "- No checks configured."}
"""

    if active_issue.get("number"):
        current = f"""# Current Task

- Issue: #{active_issue.get('number')} — {active_issue.get('title')}
- URL: {active_issue.get('url') or '-'}
- Active model: {active_issue.get('interaction_model')}
- Branch: {active_issue.get('branch')}
- Started: {active_issue.get('started_at') or '-'}

## Issue body

{active_issue.get('body') or '_No issue body captured._'}
"""
    else:
        current = "# Current Task\n\nNo active AI Rail issue. Use `rail next` or `rail start ISSUE`.\n"

    status_doc = f"""# Status

- Generated: {ctx.utc_now()}
- Branch: {ctx.current_branch()}
- Checks result: {checks}
- Git status: {status}

## Changed files
{chr(10).join(f"- {path}" for path in files) if files else "- None"}
"""

    history = "# Recent History\n\n" + "\n".join(ctx.recent_history_lines(max_history)) + "\n"

    handoff = f"""# Handoff Summary

Generated by `rail snapshot` at {ctx.utc_now()}.

## Where we are

- Project: {project_name}
- Branch: {ctx.current_branch()}
- Active issue: {('#' + str(active_issue.get('number')) + ' — ' + str(active_issue.get('title'))) if active_issue.get('number') else 'none'}
- Active model: {active_issue.get('interaction_model')}
- Checks: {checks}
- Dirty files: {len(files)}

## Next safe action

{next_safe_action(checks, bool(active_issue.get('number')), files)}
"""

    return {
        "PROJECT.md": project,
        "CURRENT_TASK.md": current,
        "STATUS.md": status_doc,
        "RECENT_HISTORY.md": history,
        "HANDOFF.md": handoff,
    }


def cmd_snapshot(argv: list[str], ctx: BrainContext) -> int:
    parser = argparse.ArgumentParser(prog="rail snapshot")
    parser.add_argument("--max-history", type=int, default=5)
    parser.add_argument("--quiet", action="store_true")
    ns = parser.parse_args(argv)

    if not ctx.rail_dir().exists():
        print("No .rail folder found. Run: rail init", file=sys.stderr)
        return 1

    docs = render_project_brain(ctx, max_history=ns.max_history)
    ctx.brain_dir().mkdir(parents=True, exist_ok=True)
    for name, content in docs.items():
        (ctx.brain_dir() / name).write_text(content, encoding="utf-8")

    if not ns.quiet:
        print("Updated AI Rail project brain:")
        for name in docs:
            print(f"- .rail/brain/{name}")
    return 0


def target_instructions(target: str) -> str:
    common = """Use this handoff as the source of truth for the current state. Do not assume missing context. Keep scope small, work only on the active issue or requested task, and ask for clarification only when the handoff is insufficient to continue safely."""
    by_target = {
        "generic": "Continue from this project state. Summarize your understanding first, then work only on the requested next step.",
        "chatgpt": "You are the reviewer/planner. Identify drift, check changed files against issue scope, check focused checks, decide whether ship is safe, and give exact next commands. Do not claim you ran commands unless evidence is included.",
        "codex": "You are the coding agent. Implement only the active issue. Read AGENTS.md and the AI Rail brain first. Do not commit, push, close issues, create roadmaps, or run broad/full tests unless explicitly asked.",
        "claude": "You are the coding agent/reviewer. Use the project brain and active task as authoritative context. Keep edits narrow, avoid broad refactors, and report changed files, focused checks, and risks.",
        "cursor": "Use the project brain as repo rules/context. Keep edits scoped to the active issue, avoid broad refactors, and do not run broad/full tests unless explicitly asked.",
        "aider": "Use this as the task brief. Edit only files relevant to the active issue, keep diffs small, run only focused requested checks, and leave commit/review/ship to AI Rail.",
    }
    return common + "\n\n" + by_target.get(target, by_target["generic"])


def render_handoff(ctx: BrainContext, target: str, max_history: int = 5, include_review: bool = False, include_checks: bool = False, max_section_chars: int = 12000) -> str:
    docs = render_project_brain(ctx, max_history=max_history)
    active_issue = ctx.active_issue_summary()
    files = ctx.changed_files()
    parts = [
        f"# AI Rail Handoff — {target}\n",
        f"Generated: {ctx.utc_now()}\n",
        "## Instruction for the next AI session\n\n" + target_instructions(target) + "\n",
        "## Quick state\n",
        f"- Branch: {ctx.current_branch()}",
        f"- Active issue: {('#' + str(active_issue.get('number')) + ' — ' + str(active_issue.get('title'))) if active_issue.get('number') else 'none'}",
        f"- Active model: {active_issue.get('interaction_model')}",
        f"- Checks result: {ctx.checks_result()}",
        f"- Changed files: {len(files)}",
        "",
        "## Project brain\n",
    ]
    for name in ["PROJECT.md", "CURRENT_TASK.md", "STATUS.md", "RECENT_HISTORY.md", "HANDOFF.md"]:
        parts.append(f"### .rail/brain/{name}\n")
        parts.append(docs[name].strip() + "\n")

    contract_files = ["AI_CONTRACT.md", "AGENTS.md", "CODEX.md", "CLAUDE.md", "CHATGPT.md", "AIDER.md"]
    existing_contracts = [(name, ctx.rail_dir() / name) for name in contract_files if (ctx.rail_dir() / name).exists()]
    if existing_contracts:
        parts.append("## AI contract files\n")
        for name, path in existing_contracts:
            parts.append(f"### .rail/{name}\n")
            parts.append(ctx.safe_read_text(path, max_chars=max_section_chars).strip() + "\n")

    if include_review:
        parts.append("## Last review pack\n")
        parts.append(ctx.safe_read_text(ctx.review_path(), "No last review pack found.", max_chars=max_section_chars).strip() + "\n")

    if include_checks:
        parts.append("## Last checks output\n")
        parts.append(ctx.safe_read_text(ctx.checks_path(), "No last checks output found.", max_chars=max_section_chars).strip() + "\n")

    parts.append("## Required response format\n")
    parts.append("- Confirm the active task you understand.\n- List any missing context or risk.\n- Then provide the smallest safe next action.\n")
    return "\n".join(parts).rstrip() + "\n"


def cmd_handoff(argv: list[str], ctx: BrainContext) -> int:
    parser = argparse.ArgumentParser(prog="rail handoff")
    parser.add_argument("--for", dest="target", choices=["generic", "chatgpt", "codex", "claude", "cursor", "aider"], default="generic")
    parser.add_argument("--copy", action="store_true", help="Copy handoff to clipboard when possible.")
    parser.add_argument("--output", help="Write handoff to a specific path instead of the default state file.")
    parser.add_argument("--max-history", type=int, default=5)
    parser.add_argument("--no-snapshot", action="store_true", help="Do not refresh .rail/brain before generating handoff.")
    parser.add_argument("--include-review", action="store_true", help="Include .rail/state/last-review.md content.")
    parser.add_argument("--include-checks", action="store_true", help="Include .rail/state/last-checks.md content.")
    parser.add_argument("--max-section-chars", type=int, default=12000)
    ns = parser.parse_args(argv)

    if not ctx.rail_dir().exists():
        print("No .rail folder found. Run: rail init", file=sys.stderr)
        return 1

    if not ns.no_snapshot:
        rc = cmd_snapshot(["--quiet", "--max-history", str(ns.max_history)], ctx)
        if rc != 0:
            return rc

    text = render_handoff(
        ctx,
        target=ns.target,
        max_history=ns.max_history,
        include_review=ns.include_review,
        include_checks=ns.include_checks,
        max_section_chars=ns.max_section_chars,
    )
    output = Path(ns.output) if ns.output else ctx.handoff_state_path(ns.target)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")

    ctx.print_text(text)
    print(f"[rail] handoff written: {output}")
    if ns.copy:
        if ctx.copy_to_clipboard(text):
            print("[rail] handoff copied to clipboard")
        else:
            print("[rail] copy requested, but no supported clipboard command was found")
    return 0


def export_path_for_target(root: Path, target: str) -> Path:
    paths = {
        "agents": root / "AGENTS.md",
        "claude": root / "CLAUDE.md",
        "cursor": root / ".cursor" / "rules" / "ai-rail.mdc",
        "aider": root / "AIDER.md",
        "copilot": root / ".github" / "copilot-instructions.md",
    }
    return paths[target]


def export_label_for_target(target: str) -> str:
    labels = {
        "agents": "AGENTS.md / Codex-compatible agents",
        "claude": "Claude Code",
        "cursor": "Cursor rules",
        "aider": "Aider",
        "copilot": "GitHub Copilot instructions",
    }
    return labels[target]


def render_export_context(ctx: BrainContext, max_history: int = 5) -> str:
    config = ctx.cfg()
    active_issue = ctx.active_issue_summary()
    files = ctx.changed_files()
    project_name = config.get("project_name") or ctx.root().name
    repository = ctx.configured_repository(config)
    issue_line = (
        f"#{active_issue.get('number')} — {active_issue.get('title')}"
        if active_issue.get("number")
        else "none"
    )
    changed = "\n".join(f"- {path}" for path in files) if files else "- None"
    history = "\n".join(ctx.recent_history_lines(max_history))
    issue_body = active_issue.get("body") or "_No active issue body captured._"
    return f"""## AI Rail project state

- Project: {project_name}
- Repository: {repository}
- Branch: {ctx.current_branch()}
- Active issue: {issue_line}
- Active model: {active_issue.get('interaction_model')}
- Checks result: {ctx.checks_result()}
- Generated: {ctx.utc_now()}

### Current task body

{issue_body}

### Changed files
{changed}

### Recent AI Rail history
{history}

### Canonical project brain files

Read these files when available. They are generated by `rail snapshot` and are the most portable source of truth for the current repo state:

- `.rail/brain/PROJECT.md`
- `.rail/brain/CURRENT_TASK.md`
- `.rail/brain/STATUS.md`
- `.rail/brain/RECENT_HISTORY.md`
- `.rail/brain/HANDOFF.md`

### AI Rail workflow rules

- Keep work scoped to the active issue unless the human explicitly changes scope.
- Prefer small diffs over broad rewrites.
- Do not commit, push, close issues, or mark tasks done unless the human explicitly asks.
- Preserve existing architecture and conventions.
- Report changed files and checks clearly.
- If context is missing, state exactly what is missing instead of guessing.
""".rstrip()


def render_tool_export(ctx: BrainContext, target: str, max_history: int = 5) -> str:
    context = render_export_context(ctx, max_history=max_history)
    target_specific = {
        "agents": """# AGENTS.md

This repository uses AI Rail. Treat this file as repo-level guidance for Codex-compatible AI coding agents.

## Agent role

You are a scoped coding agent. Implement only the active task, keep edits narrow, and leave final review/ship actions to AI Rail and the human operator.

Do not commit, close issues, create unrelated roadmaps, rewrite architecture, or run broad/full tests unless explicitly requested. Run only focused checks related to the task.""",
        "claude": """# CLAUDE.md

This repository uses AI Rail. Treat this file as Claude Code project memory and operating rules.

## Claude role

You may implement or review the active task. Before editing, summarize the active issue and the smallest safe plan. Avoid broad refactors unless explicitly requested.

Do not commit, close issues, create unrelated roadmaps, or run broad/full tests unless explicitly requested. Run only focused checks related to the task.""",
        "aider": """# AIDER.md

This repository uses AI Rail. Treat this file as the active task brief for Aider.

## Aider role

Edit only files relevant to the active issue. Keep commits and shipping outside Aider unless the human explicitly asks for them.

Do not create unrelated roadmaps, rewrite architecture, or run broad/full tests unless explicitly requested. Run only focused checks related to the task.""",
        "copilot": """# GitHub Copilot instructions

This repository uses AI Rail. Use the generated AI Rail project state below as repository guidance.

## Copilot role

Keep suggestions aligned with the active issue, existing architecture, and local checks. Avoid unrelated rewrites.

Do not suggest broad/full test runs unless the issue explicitly asks for them. Prefer focused checks related to the task.""",
    }
    if target == "cursor":
        header = """---
description: AI Rail portable project brain and workflow rules
alwaysApply: true
---

# AI Rail Cursor rules

This repository uses AI Rail. Treat this rule as always-on project context for Cursor.

## Cursor role

Keep edits scoped to the active issue. Use the project brain as authoritative context and avoid broad refactors unless explicitly requested.

Do not commit, close issues, create unrelated roadmaps, or run broad/full tests unless explicitly requested. Run only focused checks related to the task."""
    else:
        header = target_specific[target]
    return f"""{EXPORT_BEGIN}
Generated by `rail export --target {target}` at {ctx.utc_now()}.
Do not edit inside this managed block manually. Update it with `rail export`.

{header}

{context}
{EXPORT_END}
"""


def write_managed_export(ctx: BrainContext, path: Path, content: str, *, force: bool = False, dry_run: bool = False) -> tuple[bool, str]:
    if path.exists():
        existing = path.read_text(encoding="utf-8", errors="replace")
        has_begin = EXPORT_BEGIN in existing
        has_end = EXPORT_END in existing
        if has_begin and has_end:
            before = existing.split(EXPORT_BEGIN, 1)[0]
            after = existing.split(EXPORT_END, 1)[1]
            new_text = before + content + after
            action = "updated"
        elif not force:
            return False, f"refused existing unmarked file: {path} (use --force to replace with backup)"
        else:
            backup = ctx.next_backup_path(path)
            if not dry_run:
                backup.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(path, backup)
            new_text = content
            action = f"replaced with backup {backup}"
    else:
        new_text = content
        action = "created"

    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(new_text, encoding="utf-8")
    return True, f"{action}: {path}"


def cmd_export(argv: list[str], ctx: BrainContext) -> int:
    parser = argparse.ArgumentParser(prog="rail export")
    parser.add_argument("--target", action="append", choices=["all", *sorted(EXPORT_TARGETS)], help="Export target. Repeatable. Default: all.")
    parser.add_argument("--force", action="store_true", help="Replace existing unmarked files after writing a numbered .rail.bak.N backup.")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be written without changing files.")
    parser.add_argument("--no-snapshot", action="store_true", help="Do not refresh .rail/brain before exporting.")
    parser.add_argument("--max-history", type=int, default=5)
    ns = parser.parse_args(argv)

    if not ctx.rail_dir().exists():
        print("No .rail folder found. Run: rail init", file=sys.stderr)
        return 1

    if not ns.no_snapshot and not ns.dry_run:
        rc = cmd_snapshot(["--quiet", "--max-history", str(ns.max_history)], ctx)
        if rc != 0:
            return rc

    requested = ns.target or ["all"]
    targets = sorted(EXPORT_TARGETS) if "all" in requested else sorted(set(requested))

    failures: list[str] = []
    print("AI Rail tool exports:" + (" (dry run)" if ns.dry_run else ""))
    for target in targets:
        path = export_path_for_target(ctx.root(), target)
        content = render_tool_export(ctx, target, max_history=ns.max_history)
        ok, message = write_managed_export(ctx, path, content, force=ns.force, dry_run=ns.dry_run)
        label = export_label_for_target(target)
        prefix = "OK" if ok else "SKIP"
        print(f"- {prefix} {label}: {message}")
        if not ok:
            failures.append(message)

    if failures:
        print("\nSome exports were skipped to avoid overwriting human files.")
        print("Use `rail export --force` only when you intentionally want AI Rail to replace them with backups.")
        return 1
    return 0
